import { NextRequest, NextResponse } from "next/server";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { InviteMemberSchema } from "@/types/organization";

type RouteContext = { params: Promise<{ orgId: string }> };

export async function POST(request: NextRequest, context: RouteContext) {
  try {
    const { orgId } = await context.params;
    const supabase = await createSupabaseServerClient();
    const {
      data: { user },
    } = await supabase.auth.getUser();

    if (!user) {
      return NextResponse.json(
        { error: "Unauthorized", code: "UNAUTHORIZED" },
        { status: 401 },
      );
    }

    // Verify the requesting user is owner or admin
    const { data: membership, error: membershipError } = await supabase
      .from("sns_org_members")
      .select("role")
      .eq("org_id", orgId)
      .eq("user_id", user.id)
      .single();

    if (membershipError || !membership) {
      return NextResponse.json(
        { error: "Not a member of this organization", code: "FORBIDDEN" },
        { status: 403 },
      );
    }

    if (membership.role !== "owner" && membership.role !== "admin") {
      return NextResponse.json(
        {
          error: "Only owners and admins can invite members",
          code: "FORBIDDEN",
        },
        { status: 403 },
      );
    }

    const body = await request.json();
    const parsed = InviteMemberSchema.safeParse(body);
    if (!parsed.success) {
      return NextResponse.json(
        {
          error: parsed.error.issues.map((i) => i.message).join("; "),
          code: "VALIDATION_ERROR",
        },
        { status: 400 },
      );
    }

    // Check if the user is already a member
    const { data: existingUser } = await supabase
      .from("sns_users")
      .select("id")
      .eq("email", parsed.data.email)
      .single();

    if (existingUser) {
      const { data: existingMember } = await supabase
        .from("sns_org_members")
        .select("id")
        .eq("org_id", orgId)
        .eq("user_id", existingUser.id)
        .single();

      if (existingMember) {
        return NextResponse.json(
          {
            error: "User is already a member of this organization",
            code: "ALREADY_MEMBER",
          },
          { status: 409 },
        );
      }
    }

    // Check for existing pending invitation
    const { data: existingInvite } = await supabase
      .from("sns_org_invitations")
      .select("id")
      .eq("org_id", orgId)
      .eq("email", parsed.data.email)
      .is("accepted_at", null)
      .gt("expires_at", new Date().toISOString())
      .single();

    if (existingInvite) {
      return NextResponse.json(
        {
          error: "A pending invitation already exists for this email",
          code: "INVITE_EXISTS",
        },
        { status: 409 },
      );
    }

    // Create the invitation (token is auto-generated by DB default)
    const { data: invitation, error: inviteError } = await supabase
      .from("sns_org_invitations")
      .insert({
        org_id: orgId,
        email: parsed.data.email,
        role: parsed.data.role,
        invited_by: user.id,
      })
      .select()
      .single();

    if (inviteError) {
      return NextResponse.json(
        { error: inviteError.message, code: "DB_ERROR" },
        { status: 500 },
      );
    }

    return NextResponse.json(invitation, { status: 201 });
  } catch {
    return NextResponse.json(
      { error: "Internal server error", code: "INTERNAL_ERROR" },
      { status: 500 },
    );
  }
}
